---

- name: install common utilities
  include: roles/zeromq_vms/tasks/common/install.yml
  tags: install_common

- name: remove common utilities
  include: roles/zeromq_vms/tasks/common/remove.yml
  tags: remove_common

- name: launch zeromq
  include: roles/zeromq_vms/tasks/launch.yml
  tags: launch_zeromq

- name: destroy zeromq
  include: roles/zeromq_vms/tasks/destroy.yml
  tags: destroy_zeromq
