---

- name: add VM template
  include: roles/proxmox/tasks/vms/template/add.yml
  tags: add_vms_template

- name: remove VM template
  include: roles/proxmox/tasks/vms/template/remove.yml
  tags: remove_vms_template

- name: create overlay network
  include: roles/proxmox/tasks/overlay/create.yml
  tags: create_overlay

- name: destroy overlay network
  include: roles/proxmox/tasks/overlay/destroy.yml
  tags: destroy_overlay

- name: create VMs
  include: roles/proxmox/tasks/vms/create.yml
  vars:
    proxmox_vm_id: "{{ item }}"
    proxmox_prme_id: "{{ nodes[inventory_hostname]['prme_id'] }}"
  with_items: "{{ nodes[inventory_hostname]['vm_ids'] }}"
  tags: create_vms

- name: destroy VMs
  include: roles/proxmox/tasks/vms/destroy.yml
  vars:
    proxmox_vm_id: "{{ item }}"
    proxmox_prme_id: "{{ nodes[inventory_hostname]['prme_id'] }}"
  with_items: "{{ nodes[inventory_hostname]['vm_ids'] }}"
  tags: destroy_vms

- name: setup br0 as gateway bridge
  include: roles/proxmox/tasks/others/br0_as_gateway_bridge/setup.yml
  tags: setup_br0_as_primary_bridge

- name: cleanup br0 as gateway bridge
  include: roles/proxmox/tasks/others/br0_as_gateway_bridge/cleanup.yml
  tags: cleanup_br0_as_primary_bridge
