---

- name: setup hosts (should be done once after a clean install)
  include: roles/proxmox/tasks/hosts/setup.yml
  tags: setup_hosts

- name: clean hosts
  include: roles/proxmox/tasks/hosts/cleanup.yml
  tags: cleanup_hosts

- name: add VM template
  include: roles/proxmox/tasks/vms/template/add.yml
  tags: add_template

- name: remove VM template
  include: roles/proxmox/tasks/vms/template/remove.yml
  tags: remove_template

- name: install ovs_dpdk
  include: roles/proxmox/tasks/networking/overlay/switches/ovs_dpdk/build/setup.yml
  tags: install_ovs_dpdk

- name: clean ovs_dpdk
  include: roles/proxmox/tasks/networking/overlay/switches/ovs_dpdk/build/cleanup.yml
  tags: clean_ovs_dpdk

- name: setup overlay network
  include: roles/proxmox/tasks/networking/overlay/setup.yml
  tags: setup_overlay

- name: cleanup overlay network
  include: roles/proxmox/tasks/networking/overlay/cleanup.yml
  tags: cleanup_overlay

- name: create VMs
  include: roles/proxmox/tasks/vms/create.yml
  vars:
    proxmox_vm_id: "{{ item }}"
    proxmox_prme_id: "{{ nodes[inventory_hostname]['prme_id'] }}"
  with_items: "{{ nodes[inventory_hostname]['vm_ids'] }}"
  tags: create_vms

- name: destroy VMs
  include: roles/proxmox/tasks/vms/destroy.yml
  vars:
    proxmox_vm_id: "{{ item }}"
    proxmox_prme_id: "{{ nodes[inventory_hostname]['prme_id'] }}"
  with_items: "{{ nodes[inventory_hostname]['vm_ids'] }}"
  tags: destroy_vms

#- name: setup br0 as gateway bridge
#  include: roles/proxmox/tasks/networking/others/br0_as_gateway_bridge/setup.yml
#  tags: setup_br0_as_primary_bridge
#
#- name: cleanup br0 as gateway bridge
#  include: roles/proxmox/tasks/networking/others/br0_as_gateway_bridge/cleanup.yml
#  tags: cleanup_br0_as_primary_bridge

- name: add br0 flow rules
  include: roles/proxmox/tasks/networking/others/br0_add_flow_rules/setup.yml
  tags: add_br0_flow_rules

- name: remove br0 flow rules
  include: roles/proxmox/tasks/networking/others/br0_add_flow_rules/cleanup.yml
  tags: remove_br0_flow_rules
