---

- name: add hosts
  include: roles/proxmox/tasks/vms/hosts/_add.yml
  vars:
    proxmox_vm_id: "{{ _vm_id }}"
    proxmox_pve_id: "{{ nodes[hostname]['pve_id'] }}"
  with_items: "{{ nodes[hostname]['vm_ids'] }}"
  loop_control:
    loop_var: _vm_id