---

- name: install common utilities
  include: roles/workload/tasks/common/install.yml
  tags: install_common

- name: remove common utilities
  include: roles/workload/tasks/common/remove.yml
  tags: remove_common

- name: setup lb workload
  include: roles/workload/tasks/lb/setup.yml
  tags: setup_lb_workload

- name: run lb workload
  include: roles/workload/tasks/lb/run.yml
  tags: run_lb_workload

- name: cleanup lb workload
  include: roles/workload/tasks/lb/cleanup.yml
  tags: cleanup_lb_workload

- name: collect lb workload
  include: roles/workload/tasks/lb/collect.yml
  tags: collect_lb_workload
