---

- include: ssl_cert_gen.yml
  tags: ssl_gen
  when:
    "'masters' in group_names"

- include: master_build.yml
  tags: master
  when:
    "'masters' in group_names"

- include: minion_build.yaml
  tags: minion
  when:
    "'minions' in group_names"