---

proxmox_name_prefix: prme

proxmox_api_user: root@pam
proxmox_api_password: nicira

proxmox_overlay_tunnel_type: vxlan
proxmox_overlay_tunnel_size: 1450 # 1500 - 50 (VXLAN header size)
proxmox_overlay_subnet_mtu_size: "{{ proxmox_overlay_tunnel_size }}"

proxmox_base_vm_vmid: 101
proxmox_base_vm_hostname: "ubuntu-14-{{ proxmox_base_vm_vmid }}"
proxmox_base_vm_address: 10.10.10.{{ proxmox_base_vm_vmid }}
proxmox_base_vm_template_url_path: "http://pisces.cs.princeton.edu/files"
proxmox_base_vm_template_path: /var/lib/vz/dump
proxmox_base_vm_template: "vzdump-qemu-{{ proxmox_base_vm_hostname }}.vma.lzo"
proxmox_base_vm_image_path: /var/lib/vz/images
proxmox_base_vm_nbd_device: nbd0

proxmox_vm_cores: 2
proxmox_vm_sockets: 1
proxmox_vm_memory: 4096
proxmox_vm_user: mshahbaz
proxmox_vm_hostname_prefix: k8s-node-
proxmox_vm_network_interface: eth0
proxmox_vm_network_interface_mtu_size: "{{ proxmox_overlay_subnet_mtu_size }}"
proxmox_vm_network_address_prefix: 192.168. # Note: make sure vmbr0 on Proxmox VEs has an IP in this range
proxmox_vm_network_netmask: 255.255.255.0
proxmox_vm_network_network_postfix: 0
proxmox_vm_network_broadcast_postfix: 255
proxmox_vm_network_gateway_postfix: 1
proxmox_vm_dns_nameservers: 10.20.20.1
proxmox_vm_dns_search: eng.vmware.com

