---

fanin_sub:
  prme_id: 1
  vm_id: 120

fanin_pub_cmds: 'msleep (1);' # e.g. msleep(1);

fanin_pub_count_per_node: 1

fanin_pubsub_nodes:
  prme1-k8s-node-120:
    type: "subscriber"
    host: "prme-nsx-perf-001"

  prme2-k8s-node-120:
    type: "publisher"
    sub: "{{ fanin_sub }}"
    count: "{{ fanin_pub_count_per_node }}"

  prme3-k8s-node-120:
    type: "publisher"
    sub: "{{ fanin_sub }}"
    count: "{{ fanin_pub_count_per_node }}"
