---

- name: ensure that pve-no-subscription repository is present in the /etc/apt/sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: "deb http://download.proxmox.com/debian/pve jessie pve-no-subscription"
    state: present

- name: update cache
  apt:
    update_cache: yes
  ignore_errors: yes

- name: install essential utilities
  shell: apt-get -y install cpulimit expect htop tmux unzip git python-pip python-yaml python-setuptools build-essential dh-autoreconf pve-headers-`uname -r` pkg-config cmake uuid-dev python-dev python-psutil stress-ng

- name: install essential utilities
  shell: pip install proxmoxer

- name: update .bashrc file
  template:
    src: roles/proxmox/templates/host_bashrc.j2
    dest: /root/.bashrc
    backup: yes

- name: update interfaces file
  template:
    src: roles/proxmox/templates/host_interfaces_static/{{ inventory_hostname }}.j2
    dest: /etc/network/interfaces
    backup: yes

