---

- name: ensure that pve-no-subscription repository is present in the /etc/apt/sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: "deb http://download.proxmox.com/debian/pve jessie pve-no-subscription"
    state: present

- name: update cache
  apt:
    update_cache: yes
  ignore_errors: yes

- name: install vim
  apt:
    name: vim

- name: install lshw
  apt:
    name: lshw

- name: update .bashrc file
  template:
    src: roles/proxmox/templates/host_bashrc.j2
    dest: /root/.bashrc
    backup: yes

- name: update interfaces file
  template:
    src: roles/proxmox/templates/host_interfaces_static/{{ inventory_hostname }}.j2
    dest: /etc/network/interfaces
    backup: yes

