---

- name: destory broker stats script
  shell: pkill -u root -f log_broker_stats
  when: '"broker" in broker_pubsub_nodes[inventory_hostname].type'
  failed_when: false

- name: remove log_broker_stats.sh script
  file:
    path: /tmp/log_broker_stats.sh
    state: absent
  when: '"broker" in broker_pubsub_nodes[inventory_hostname].type'

- name: destory radio_*
  shell: pkill -u root -f radio_
  when: '"publisher" in broker_pubsub_nodes[inventory_hostname].type'
  failed_when: false

- name: remove radio_* files and executables
  shell: cd /root/libzmq/tests;
         rm -f radio_*
  when: '"publisher" in broker_pubsub_nodes[inventory_hostname].type'

- name: destory broker
  shell: pkill -u root -f broker
  when: '"broker" in broker_pubsub_nodes[inventory_hostname].type'
  failed_when: false

- name: remove broker files and executables
  shell: cd /root/libzmq/tests;
         rm -f broker*
  when: '"broker" in broker_pubsub_nodes[inventory_hostname].type'

- name: destory dish_*
  shell: pkill -u root -f dish_
  when: '"subscriber" in broker_pubsub_nodes[inventory_hostname].type'
  failed_when: false

- name: remove dish_* files and executables
  shell: cd /root/libzmq/tests;
         rm -f dish_*
  when: '"subscriber" in broker_pubsub_nodes[inventory_hostname].type'
