---

- name: add VM to {{ inventory_hostname }}-vms group
  add_host:
    name: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_base_vm_vmid }}"
    instance_name: "{{ proxmox_vm_hostname_prefix }}{{ proxmox_base_vm_vmid }}"
    groups: "{{ inventory_hostname }}-vms"
    ansible_user: "{{ proxmox_vm_user }}"
    ansible_ssh_common_args: "{{ proxmox_ssh_common_args }}"

- name: clone VM
  proxmox_kvm:
    state: present
    node: "{{ inventory_hostname }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    clone: "{{ proxmox_base_vm_hostname }}"
    vmid: "{{ proxmox_base_vm_vmid }}"
    name: "{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_vmid }}"
    newid: "{{ proxmox_vm_vmid }}"
  delegate_to: localhost

- name: start VM
  proxmox_kvm:
    state: started
    node: "{{ inventory_hostname }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    name: "{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_vmid }}"
    vmid: "{{ proxmox_vm_vmid }}"
  delegate_to: localhost

- name: wait for ssh to come up
  wait_for:
    host: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_base_vm_vmid }}"
    port: 22
    delay: 1
    state: started
  delegate_to: "{{ inventory_hostname }}"

- name: change ip address in /etc/network/interfaces
  template:
    src: roles/proxmox/templates/interfaces_static.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    backup: yes
  delegate_to: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_base_vm_vmid }}"
  become: true

- name: update hostname in /etc/hostname
  replace:
    path: /etc/hostname
    regexp: "{{ proxmox_base_vm_hostname }}"
    replace: "{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_vmid }}"
  delegate_to: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_base_vm_vmid }}"
  become: true

- name: update ip address in /etc/hosts
  replace:
    path: /etc/hosts
    regexp: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_base_vm_vmid }}"
    replace: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_vm_vmid }}"
  delegate_to: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_base_vm_vmid }}"
  become: true

- name: update hostname in /etc/hosts
  replace:
    path: /etc/hosts
    regexp: "{{ proxmox_base_vm_hostname }}"
    replace: "{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_vmid }}"
  delegate_to: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_base_vm_vmid }}"
  become: true

- name: add VM to {{ inventory_hostname }}-vms groups
  add_host:
    name: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_vm_vmid }}"
    instance_name: "{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_vmid }}"
    groups: "{{ inventory_hostname }}-vms"
    ansible_user: "{{ proxmox_vm_user }}"
    ansible_ssh_common_args: "{{ proxmox_ssh_common_args }}"

- name: reboot VM
  command: /sbin/reboot
  delegate_to: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_base_vm_vmid }}"
  become: true

- name: wait for ssh to come up
  wait_for:
    host: "{{ proxmox_vm_network_address_prefix }}{{ proxmox_vm_vmid }}"
    port: 22
    delay: 1
    state: started
  delegate_to: "{{ inventory_hostname }}"

- name: ensure that {{ inventory_hostname }}-vms group exists in the inventory file
  lineinfile:
    path: "{{ inventory_file }}"
    line: "[{{ inventory_hostname }}-vms]"
    state: present
  delegate_to: localhost

- name: add VM to the {{ inventory_hostname }}-vms group in the inventory file
  lineinfile:
    path: "{{ inventory_file }}"
    line: "{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_vmid }} ansible_host={{ proxmox_vm_network_address_prefix }}{{ proxmox_vm_vmid }} ansible_user={{ proxmox_vm_user }} ansible_ssh_common_args='{{ proxmox_ssh_common_args }}'"
    insertafter: "^\\[{{ inventory_hostname }}-vms\\]"
    state: present
  delegate_to: localhost

- name: refresh invetory
  meta: refresh_inventory

#- debug:
#    msg: "{{ groups }}"