---

- name: remove VM from the {{ inventory_hostname }}-vms group in the inventory file
  lineinfile:
    path: "{{ inventory_file }}"
    line: "{{ inventory_hostname }}-{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_vmid }} ansible_host={{ proxmox_vm_network_address_prefix }}{{ proxmox_vm_vmid }} ansible_user={{ proxmox_vm_user }} ansible_ssh_common_args='{{ proxmox_ssh_common_args }}'"
    state: absent
  delegate_to: localhost

- name: remove {{ inventory_hostname }}-vms group from the inventory file
  lineinfile:
    path: "{{ inventory_file }}"
    line: "[{{ inventory_hostname }}-vms]"
    state: absent
  delegate_to: localhost

- name: stop VM
  proxmox_kvm:
    state: stopped
    node: "{{ inventory_hostname }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    name: "{{ inventory_hostname }}-{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_vmid }}"
    vmid: "{{ proxmox_vm_vmid }}"
  delegate_to: localhost

- name: destroy VM
  proxmox_kvm:
    state: absent
    node: "{{ inventory_hostname }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    name: "{{ inventory_hostname }}-{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_vmid }}"
    vmid: "{{ proxmox_vm_vmid }}"
  delegate_to: localhost

#- debug:
#    msg: "{{ groups }}"