---

- name: add VM template
  include: add_vm_template.yml
  tags: add_vm_template

- name: create VMs
  include: create_vms.yml
  vars:
    proxmox_vm_id: "{{ item }}"
    proxmox_pve_id: "{{ nodes[inventory_hostname]['pve_id'] }}"
    proxmox_vm_network_address_prefix: "{{ nodes[inventory_hostname]['address_prefix'] }}"
  with_items: "{{ nodes[inventory_hostname]['vm_ids'] }}"
  tags: create_vms

- name: destroy VMs
  include: destroy_vms.yml
  vars:
    proxmox_vm_id: "{{ item }}"
    proxmox_pve_id: "{{ nodes[inventory_hostname]['pve_id'] }}"
    proxmox_vm_network_address_prefix: "{{ nodes[inventory_hostname]['address_prefix'] }}"
  with_items: "{{ nodes[inventory_hostname]['vm_ids'] }}"
  tags: destroy_vms

- name: remove VM template
  include: remove_vm_template.yml
  tags: remove_vm_template
