---

- name: create VMs
  include: create_vms.yml
  vars:
    proxmox_vm_vmid: "{{ item }}"
  with_items: "{{ proxmox_vm_vmids }}"
  tags: create_vms

- name: destroy VMs
  include: destroy_vms.yml
  vars:
    proxmox_vm_vmid: "{{ item }}"
  with_items: "{{ proxmox_vm_vmids }}"
  tags: destroy_vms