---

- name: create VMs
  include: create_vms.yml
  vars:
    proxmox_vmid: "{{ item }}"
  with_items: "{{ proxmox_vmids }}"
  tags: create_vms

- name: remove VMs
  include: remove_vms.yml
  vars:
    proxmox_vmid: "{{ item }}"
  with_items: "{{ proxmox_vmids }}"
  tags: remove_vms