---

- name: provision zeromq
  hosts: prme*k8s-node-*
  gather_facts: false

  vars_files:
    - "vars/proxmox/defaults.yml"
    - "vars/zeromq_vms/main.yml"
    - "vars/zeromq_vms/configs/fanout/{{ configs.fanout }}.yml"
    - "vars/zeromq_vms/configs/fanin/{{ configs.fanin }}.yml"
    - "vars/zeromq_vms/configs/broker/{{ configs.broker }}.yml"

  roles:
    - zeromq_vms
