---

- name: provision zeromq
  hosts: prme*k8s-node-*
  gather_facts: false

  vars_files:
    - "vars/proxmox/defaults.yml"
    - "vars/zeromq_vms/main.yml"
    - "vars/zeromq_vms/configs/{{ configs }}.yml"

  roles:
    - zeromq_vms
