---

- name: provision feedback scheme
  hosts: prme*k8s-node-*
  gather_facts: false

  vars_files:
    - "vars/kubernetes/main.yml"
    - "vars/kubernetes/configs/{{ configs }}.yml"
    - "vars/kubernetes/defaults.yml"
    - "vars/feedback.yml"

  roles:
    - feedback
