---

- name: provision kubernetes cluster
  hosts: prme*k8s-node-*
  gather_facts: false
  become: true

  vars_files:
    - "vars/kubernetes.yml"
    - "vars/kubernetes.defaults.yml"
    - "vars/workload.yml"

  roles:
    - workload
