---

- name: provision workload
  hosts: prme*k8s-node-*
  gather_facts: false

  vars_files:
    - "vars/kubernetes/main.yml"
    - "vars/kubernetes/networking.yml"
    - "vars/kubernetes/defaults.yml"
    - "vars/workload.yml"

  roles:
    - workload
