---

- name: launch tx
  shell: cd /root/MoonGen;
         ./build/MoonGen ./examples/custom/{{ tester.moongen.benchmark }} {{ tester.moongen.ports }} &
         cd /root
  when: 'inventory_hostname in "prme-nsx-perf-004"'

- name: launch rx
  shell: cd /root/MoonGen;
         ./build/MoonGen ./examples/custom/packet-rx.lua {{ tester.moongen.ports }} | \
         grep "Received \|Total " > /tmp/{{ tester.moongen.benchmark }}.log &
         cd /root
  when: 'inventory_hostname in "prme-nsx-perf-006"'
