---

- name: Provision VM:{{ proxmox_provision_vmid }}
  block:
  - name: Add VM:{{ proxmox_provision_clone_vmid }} to {{ proxmox_name }}_servers groups
    add_host:
      name: "{{ proxmox_provision_ip_prefix }}{{ proxmox_provision_clone_vmid }}"
      instance_name: "{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_clone_vmid }}"
      groups: "{{ proxmox_name }}_servers"

  - name: Clone VM:{{ proxmox_provision_vmid }}
    proxmox_kvm:
      state: present
      node: "{{ proxmox_node }}"
      api_user: "{{ proxmox_api_user }}"
      api_password: "{{ proxmox_api_password }}"
      api_host: "{{ proxmox_api_host }}"
      clone: "{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_clone_vmid }}"
      vmid: "{{ proxmox_provision_clone_vmid }}"
      name: "{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_vmid }}"
      newid: "{{ proxmox_provision_vmid }}"
    delegate_to: localhost

  - name: Start VM:{{ proxmox_provision_vmid }}
    proxmox_kvm:
      state: started
      node: "{{ proxmox_node }}"
      api_user: "{{ proxmox_api_user }}"
      api_password: "{{ proxmox_api_password }}"
      api_host: "{{ proxmox_api_host }}"
      name: "{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_vmid }}"
      vmid: "{{ proxmox_provision_vmid }}"
    delegate_to: localhost

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ proxmox_provision_ip_prefix }}{{ proxmox_provision_clone_vmid }}"
      port: 22
      delay: 1
      state: started
    delegate_to: "{{ proxmox_name }}"

  - name: Change IP address in /etc/network/interfaces
    template: src=roles/proxmox-provision/templates/interfaces_static.j2 dest=/etc/network/interfaces owner=root group=root mode=0644 backup=yes
    vars:
      proxmox_provision_address: "{{ proxmox_provision_ip_prefix }}{{ proxmox_provision_vmid }}"
    delegate_to: 10.10.10.{{ proxmox_provision_clone_vmid }}
    become: true

  - name: Update hostname in /etc/hostname
    replace:
      path: /etc/hostname
      regexp: "ubuntu-14-{{ proxmox_provision_clone_vmid }}"
      replace: "ubuntu-14-{{ proxmox_provision_vmid }}"
    delegate_to: 10.10.10.{{ proxmox_provision_clone_vmid }}
    become: true

  - name: Update IP address in /etc/hosts
    replace:
      path: /etc/hosts
      regexp: "{{ proxmox_provision_ip_prefix }}{{ proxmox_provision_clone_vmid }}"
      replace: "{{ proxmox_provision_ip_prefix }}{{ proxmox_provision_vmid }}"
    delegate_to: 10.10.10.{{ proxmox_provision_clone_vmid }}
    become: true

  - name: Update hostname in /etc/hosts
    replace:
      path: /etc/hosts
      regexp: "ubuntu-14-{{ proxmox_provision_clone_vmid }}"
      replace: "ubuntu-14-{{ proxmox_provision_vmid }}"
    delegate_to: 10.10.10.{{ proxmox_provision_clone_vmid }}
    become: true

  - name: Add VM:{{ proxmox_provision_vmid }} to {{ proxmox_name }}_servers groups
    add_host:
      name: "{{ proxmox_provision_ip_prefix }}{{ proxmox_provision_vmid }}"
      instance_name: "{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_vmid }}"
      groups: "{{ proxmox_name }}_servers"

  - name: Reboot VM:{{ proxmox_provision_vmid }}
    command: /sbin/reboot
    delegate_to: 10.10.10.{{ proxmox_provision_clone_vmid }}
    become: true

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ proxmox_provision_ip_prefix }}{{ proxmox_provision_vmid }}"
      port: 22
      delay: 1
      state: started
    delegate_to: "{{ proxmox_name }}"

  - name: Check if {{ proxmox_name }}_data_servers group exists in the inventory file
    lineinfile:
      path: ./inventory.ini
      regexp: "^\\[{{ proxmox_name }}_data_servers\\]"
      line: "[{{ proxmox_name }}_data_servers]"
      state: present

  - name: Add VM:{{ proxmox_provision_vmid }} to the {{ proxmox_name }}_servers group in the inventory file
    replace:
      path: ./inventory.ini
      regexp: "^\\[{{ proxmox_name }}_servers\\]"
      replace: "[{{ proxmox_name }}_servers]\n{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_vmid }} ansible_host={{ proxmox_provision_ip_prefix }}{{ proxmox_provision_vmid }}"

  - name: Add VM:{{ proxmox_provision_vmid }} to the {{ proxmox_name }}_data_servers group in the inventory file
    replace:
      path: ./inventory.ini
      regexp: "^\\[{{ proxmox_name }}_data_servers\\]"
      replace: "[{{ proxmox_name }}_data_servers]\n{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_vmid }} ansible_host={{ proxmox_provision_ip_prefix }}{{ proxmox_provision_vmid }}"

#  - name: Testing
#    command: hostname
#    register: output
#    delegate_to: 10.10.10.{{ proxmox_provision_clone_vmid }}
#
#  - debug:
#      msg: "{{ output }}"
#    delegate_to: 10.10.10.{{ proxmox_provision_clone_vmid }}

#  - debug:
#      msg: "{{ groups }}"

  when: proxmox_provision and '{{ proxmox_name }}_data_servers' not in groups

- name: Remove VM:{{ proxmox_provision_vmid }}
  block:
  - name: Remove VM:{{ proxmox_provision_vmid }} from the inventory file
    lineinfile:
      path: ./inventory.ini
      regexp: "^{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_vmid }} ansible_host={{ proxmox_provision_ip_prefix }}{{ proxmox_provision_vmid }}"
      state: absent

  - name: Remove {{ proxmox_name }}_data_servers group from the inventory file
    lineinfile:
      path: ./inventory.ini
      regexp: "^\\[{{ proxmox_name }}_data_servers\\]"
      state: absent

  - name: Stop VM:{{ proxmox_provision_vmid }}
    proxmox_kvm:
      state: stopped
      node: "{{ proxmox_node }}"
      api_user: "{{ proxmox_api_user }}"
      api_password: "{{ proxmox_api_password }}"
      api_host: "{{ proxmox_api_host }}"
      name: "{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_vmid }}"
      vmid: "{{ proxmox_provision_vmid }}"
    delegate_to: localhost

  - name: Destroy VM:{{ proxmox_provision_vmid }}
    proxmox_kvm:
      state: absent
      node: "{{ proxmox_node }}"
      api_user: "{{ proxmox_api_user }}"
      api_password: "{{ proxmox_api_password }}"
      api_host: "{{ proxmox_api_host }}"
      name: "{{ proxmox_provision_hostname_prefix }}-{{ proxmox_provision_vmid }}"
      vmid: "{{ proxmox_provision_vmid }}"
    delegate_to: localhost

  when: not proxmox_provision and '{{ proxmox_name }}_data_servers' in groups