---

- name: install common utilities
  include: roles/mqtt_vms/tasks/common/install.yml
  tags: install_common

- name: remove common utilities
  include: roles/mqtt_vms/tasks/common/remove.yml
  tags: remove_common

- name: launch mqtt
  include: roles/mqtt_vms/tasks/launch.yml
  tags: launch_mqtt

- name: destroy mqtt
  include: roles/mqtt_vms/tasks/destroy.yml
  tags: destroy_mqtt
