---

- name: stop docker service
  service:
    name: docker
    state: stopped

- name: update k8s_overlay_subnet_first_octect
  shell: "var={{ k8s_overlay_subnet_first_octect_base }};var=$((var+{{ pve_id }}));echo $var"
  register: k8s_overlay_subnet_first_octect

- name: update docker subnet
  lineinfile:
    path: "{{ docker_defautl_config }}"
    line: 'DOCKER_OPTS="--bip={{ k8s_overlay_subnet_first_octect.stdout }}.{{ vm_id }}.0.1/{{ k8s_overlay_subnet_mask }}"'
    state: present
  become: true

- name: start docker service
  service:
    name: docker
    state: started

- name: create an ovs bridge 'br0'
  openvswitch_bridge:
    bridge: br0
    state: present
  become: true

- name: add br0 to docker0 bridge
  shell: brctl addif docker0 br0
  become: true

- name: create a gre tunnel using br0
  openvswitch_port:
    bridge: br0
    port: gre0
    state: present
    set: interface gre0 type=gre options:remote_ip={{ item }}
  with_items: "{{ nodes[inventory_hostname]['remote_nodes'] }}"
  become: true

- name: add static route for overlay traffic
  shell: ip route add {{ k8s_overlay_subnet_first_octect.stdout }}.0.0.0/8 dev docker0
  become: true

#- debug:
#    msg: "{{ k8s_overlay_subnet_first_octect.stdout }}"


