---

- name: create overlay network
  include: roles/kubernetes/tasks/overlay/create.yml
  tags: create_overlay

- name: destroy overlay network
  include: roles/kubernetes/tasks/overlay/destroy.yml
  tags: destroy_overlay

- name: create k8s cluster
  include: roles/kubernetes/tasks/cluster/create.yml
  tags: create_cluster

- name: destroy k8s cluster
  include: roles/kubernetes/tasks/cluster/destroy.yml
  tags: destroy_cluster

