---

- name: create VMs
  include: create_vms.yml
  vars:
    proxmox_vmid: "{{ item }}"
  with_items: "{{ proxmox_vmids }}"
#  when: provision_proxmox
  tags: create_vms

- name: remove VMs
  include: remove_vms.yml
  vars:
    proxmox_vmid: "{{ item }}"
  with_items: "{{ proxmox_vmids }}"
#  when: not provision_proxmox
  tags: remove_vms