---

- name: Create VM
  include: create_vm.yml
  vars:
    proxmox_vmid: "{{ item }}"
  with_items: "{{ proxmox_vmids }}"
  when: provision_proxmox

- name: Remove VM
  include: remove_vm.yml
  vars:
    proxmox_vmid: "{{ item }}"
  with_items: "{{ proxmox_vmids }}"
  when: not provision_proxmox
