---

overlay:
  prme-nsx-perf-001:
    interfaces:
      vmware_switch: eth5
      tor_network: eth2
    options:
      eth2:
        pci_id: "0000:42:00.0"
        address: 172.16.140.158
        netmask: 255.255.255.0
      eth5:
        pci_id: "0000:42:00.1"
        address: 172.16.40.158
        netmask: 255.255.255.0
    dpdk:
      cpu_mask: '0x0002'
      memory_channels: 4
  prme-nsx-perf-002:
    interfaces:
      vmware_switch: eth5
      tor_network: eth2
    options:
      eth2:
        pci_id: "0000:42:00.0"
        address: 172.16.140.159
        netmask: 255.255.255.0
      eth5:
        pci_id: "0000:42:00.1"
        address: 172.16.40.159
        netmask: 255.255.255.0
    dpdk:
      cpu_mask: '0x0002'
      memory_channels: 4
  prme-nsx-perf-003:
    interfaces:
      vmware_switch: eth5
      tor_network: eth2
    options:
      eth2:
        pci_id: "0000:42:00.0"
        address: 172.16.140.160
        netmask: 255.255.255.0
      eth5:
        pci_id: "0000:42:00.1"
        address: 172.16.40.160
        netmask: 255.255.255.0
    dpdk:
      cpu_mask: '0x0002'
      memory_channels: 4
  prme-nsx-perf-007:
    interfaces:
      vmware_switch: eth2
      tor_network: eth5
    options:
      eth2:
        pci_id: "0000:42:00.0"
        address: 172.16.40.96
        netmask: 255.255.255.0
      eth5:
        pci_id: "0000:42:00.1"
        address: 172.16.140.96
        netmask: 255.255.255.0
    dpdk:
      cpu_mask: '0x0002'
      memory_channels: 4
  prme-nsx-perf-008:
    interfaces:
      vmware_switch: eth2
      tor_network: eth5
    options:
      eth2:
        pci_id: "0000:42:00.0"
        address: 172.16.40.97
        netmask: 255.255.255.0
      eth5:
        pci_id: "0000:42:00.1"
        address: 172.16.140.97
        netmask: 255.255.255.0
    dpdk:
      cpu_mask: '0x0002'
      memory_channels: 4
  prme-nsx-perf-009:
    interfaces:
      vmware_switch: eth2
      tor_network: eth5
    options:
      eth2:
        pci_id: "0000:42:00.0"
        address: 172.16.40.98
        netmask: 255.255.255.0
      eth5:
        pci_id: "0000:42:00.1"
        address: 172.16.140.98
        netmask: 255.255.255.0
    dpdk:
      cpu_mask: '0x0002'
      memory_channels: 4

switches:
  pisces:
    cflags: '-O2 -Wno-cast-align' # Options: -g or ''
    p4_programs:
      base_dir: files
