---

- name: ensure repository key is installed
  apt_key:
    id: "{{ docker_apt_key_id }}"
    keyserver: "{{ docker_apt_keyserver }}"
    state: present

- name: ensure docker registry is available
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    update_cache: yes
    state: present

- name: ensure docker and dependencies are installed
  apt:
    name: docker-engine

- name: add user {{ ansible_user }} to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: restart docker service
  service:
    name: docker
    state: restarted

- name: Get docker compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755

#- debug:
#    msg: "{{ inventory_hostname }}"