---

- name: remove repository key if installed
  apt_key:
    id: "{{ docker_apt_key_id }}"
    keyserver: "{{ docker_apt_keyserver }}"
    state: absent

- name: remove docker registry if available
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    update_cache: yes
    state: absent

- name: uninstall docker and dependencies
  apt:
    name: docker-engine
    purge: yes
    state: absent

- name: remove docker compose
  file:
    path: /usr/local/bin/docker-compose
    state: absent

#- debug:
#    msg: "{{inventory_hostname}}"
