---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    proxmox_name: pve1
    proxmox_node: mshahbaz-poweredge-1-pve
    proxmox_api_host: 128.112.168.26
    proxmox_provision_vmids: [ 120, ]
    proxmox_provision: false

  tasks:
    - include_role:
        name: proxmox-provision
      vars:
        proxmox_provision_vmid: "{{ item }}"
      with_items: "{{ proxmox_provision_vmids }}"

- hosts: servers
  gather_facts: false
  tasks:
    - command: hostname
      register: output

    - debug:
        msg: "{{ output.stdout }}"
