---

master:
  prme_id: 1
  vm_id: 120

nodes:
  prme1-k8s-node-120:
    type: "master"
    master: "{{ master }}"
  prme2-k8s-node-120:
    type: "minion"
    master: "{{ master }}"
  prme3-k8s-node-120:
    type: "minion"
    master: "{{ master }}"
  prme7-k8s-node-120:
    type: "minion"
    master: "{{ master }}"
  prme8-k8s-node-120:
    type: "minion"
    master: "{{ master }}"
  prme9-k8s-node-120:
    type: "minion"
    master: "{{ master }}"

networking:
  prme1-k8s-node-120:
    remote_nodes:
      - prme_id: 2
        vm_id: 120
      - prme_id: 3
        vm_id: 120
      - prme_id: 7
        vm_id: 120
      - prme_id: 8
        vm_id: 120
      - prme_id: 9
        vm_id: 120
  prme2-k8s-node-120:
    remote_nodes:
      - prme_id: 1
        vm_id: 120
      - prme_id: 3
        vm_id: 120
      - prme_id: 7
        vm_id: 120
      - prme_id: 8
        vm_id: 120
      - prme_id: 9
        vm_id: 120
  prme3-k8s-node-120:
    remote_nodes:
      - prme_id: 1
        vm_id: 120
      - prme_id: 2
        vm_id: 120
      - prme_id: 7
        vm_id: 120
      - prme_id: 8
        vm_id: 120
      - prme_id: 9
        vm_id: 120
  prme7-k8s-node-120:
    remote_nodes:
      - prme_id: 1
        vm_id: 120
      - prme_id: 2
        vm_id: 120
      - prme_id: 3
        vm_id: 120
      - prme_id: 8
        vm_id: 120
      - prme_id: 9
        vm_id: 120
  prme8-k8s-node-120:
    remote_nodes:
      - prme_id: 1
        vm_id: 120
      - prme_id: 2
        vm_id: 120
      - prme_id: 3
        vm_id: 120
      - prme_id: 7
        vm_id: 120
      - prme_id: 9
        vm_id: 120
  prme9-k8s-node-120:
    remote_nodes:
      - prme_id: 1
        vm_id: 120
      - prme_id: 2
        vm_id: 120
      - prme_id: 3
        vm_id: 120
      - prme_id: 7
        vm_id: 120
      - prme_id: 8
        vm_id: 120
