---

- name: install pisces
  include: roles/proxmox_tor/tasks/networking/switches/pisces/build/setup.yml
  tags: install_pisces

- name: clean pisces
  include: roles/proxmox_tor/tasks/networking/switches/pisces/build/cleanup.yml
  tags: clean_pisces

- name: setup tor network
  include: roles/proxmox_tor/tasks/networking/setup.yml
  tags: setup_tor_network

- name: cleanup tor network
  include: roles/proxmox_tor/tasks/networking/cleanup.yml
  tags: cleanup_tor_network
