---

- name: setup tor network
  include: roles/proxmox_tor/tasks/networking/setup.yml
  tags: setup_tor_network

- name: cleanup tor network
  include: roles/proxmox_tor/tasks/networking/cleanup.yml
  tags: cleanup_tor_network
