---

- name: cleanup pisces
  include: roles/proxmox_tor/tasks/networking/switches/pisces/cleanup.yml
  when: 'tor_switch.type == "pisces"'

- name: cleanup ovs (kernel)
  include: roles/proxmox_tor/tasks/networking/switches/ovs_kernel/cleanup.yml
  when: 'tor_switch.type == "ovs_kernel"'

- name: cleanup linux bridge
  include: roles/proxmox_tor/tasks/networking/switches/linux_bridge/cleanup.yml
  when: 'tor_switch.type == "linux_bridge"'
