---

- name: remove bridge-utils
  become: true
  apt:
    name: bridge-utils
    purge: yes
    state: absent

- name: remove unzip
  become: true
  apt:
    name: unzip
    purge: yes
    state: absent

- name: update cache
  become: true
  apt:
    update_cache: yes

