---

- name: create an ovs bridge br0
  shell: cd /root/ovs/utilities;
         ./ovs-vsctl add-br br0 -- set bridge br0 datapath_type=netdev;
         ./ovs-vsctl set bridge br0 protocols=OpenFlow15;
         cd /root

- name: bring up br0
  shell: ip link set dev br0 up

- name: add interfaces to br0
  shell: cd /root/ovs/utilities;
         ./ovs-vsctl add-port br0 dpdk{{ item }} -- set Interface dpdk{{ item }} type=dpdk;
         cd /root
  with_sequence: start=0 end={{ nodes[inventory_hostname]['interfaces'] | length - 1 }} format=%d
