---

- name: remove interfaces from br0
  openvswitch_port:
    bridge: br0
    port: "{{ item }}"
    state: absent
  with_items: "{{ nodes[inventory_hostname]['interfaces'] }}"

- name: bring down interfaces
  shell: ip link set dev {{ item }} down
  with_items: "{{ nodes[inventory_hostname]['interfaces'] }}"

- name: bring down br0
  shell: ip link set dev br0 down

- name: disable stp on br0 # TODO: change this to flow rules
  command: ovs-vsctl set bridge br0 stp_enable=false

- name: delete ovs bridge br0
  openvswitch_bridge:
    bridge: br0
    state: absent

- name: remove common utilities
  include: roles/proxmox_tor/tasks/networking/common/remove.yml
