---

- name: install common utilities
  include: roles/proxmox_tor/tasks/networking/common/install.yml

- name: create an ovs bridge br0
  openvswitch_bridge:
    bridge: br0
    state: present

- name: enable stp on br0 # TODO: change this to flow rules
  command: ovs-vsctl set bridge br0 stp_enable=true

- name: bring up br0
  shell: ip link set dev br0 up

- name: bring up interfaces
  shell: ip link set dev {{ item }} up
  with_items: "{{ nodes[inventory_hostname]['interfaces'] }}"

- name: add interfaces to br0
  openvswitch_port:
    bridge: br0
    port: "{{ item }}"
    state: present
  with_items: "{{ nodes[inventory_hostname]['interfaces'] }}"
