---

- name: remove hosts from the inventory file
  include: roles/proxmox/tasks/vms/hosts/remove.yml
  vars:
    hostname: "{{ _hostname }}"
  with_items: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: _hostname

- name: unmount VM parition
  shell: umount /mnt/vm{{ proxmox_vm_id }}
#  ignore_errors: yes
  failed_when: false

- name: disconnect VM image as nbd device
  shell: qemu-nbd --disconnect /dev/{{ proxmox_base_vm_nbd_device }}
#  ignore_errors: yes
  failed_when: false

- name: stop VM
  proxmox_kvm:
    state: stopped
    node: "{{ inventory_hostname }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    name: "{{ proxmox_name_prefix }}{{ proxmox_pve_id }}-{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_id }}"
    vmid: "{{ proxmox_vm_id }}"
  delegate_to: localhost

- name: destroy VM
  proxmox_kvm:
    state: absent
    node: "{{ inventory_hostname }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    name: "{{ proxmox_name_prefix }}{{ proxmox_pve_id }}-{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_id }}"
    vmid: "{{ proxmox_vm_id }}"
  delegate_to: localhost
