---

- set_fact:
    remote_hostname: prme-nsx-perf-00{{ remote_node.prme_id }}
    remote_interface: ansible_{{ remote_node.interface }}

- name: add underlay flow rule for the remote interface in br0
  shell: cd /root/ovs/utilities;
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=0,priority=10,ipv4__dstAddr={{ hostvars[remote_hostname][remote_interface].ipv4.address | ipaddr('address') | ipaddr('int') }} actions=1";
         cd /root
