---

- set_fact:
    remote_hostname: prme-nsx-perf-00{{ remote_node.prme_id }}
    remote_interface: ansible_{{ remote_node.interface }}

- name: delete static arp entry
  shell: arp -d {{ hostvars[remote_hostname][remote_interface].ipv4.address }}
