---

- name: remove iptables rule to filter traffic coming from eth0 belonging to the overlay subnet
  shell: iptables -D INPUT -s {{ proxmox_vm_network_address_prefix }}0.0/16 -i eth0 -j DROP

- name: delete {{ proxmox_overlay_tunnel_type }} tunnels for each endpoint using br0
  include: roles/proxmox/tasks/networking/overlay/del_tunnel.yml remote_node="{{ item }}"
  with_items: "{{ networking[inventory_hostname]['remote_nodes'] }}"

- name: reset mtu size to 1500
  command: ip link set mtu 1500 dev br0

- name: remove br0 from vmbr0 bridge
  shell: brctl delif vmbr0 br0

- name: delete ovs bridge br0
  openvswitch_bridge:
    bridge: br0
    state: absent

- name: remove static route for overlay traffic
  shell: ip route del {{ proxmox_vm_network_address_prefix }}0.0/16 dev vmbr0

- name: remove common utilities
  include: roles/proxmox/tasks/networking/common/remove.yml
