---

- name: add flow rules for bitmap matching
  shell: cd /root/ovs/utilities;
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0x1/0x0F actions=1";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0x2/0x0F actions=2";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0x4/0x0F actions=4";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0x8/0x0F actions=3";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0x3/0x0F actions=2,1";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0x5/0x0F actions=4,1";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0x9/0x0F actions=3,1";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0x6/0x0F actions=4,2";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0xA/0x0F actions=3,2";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0xC/0x0F actions=3,4";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0x7/0x0F actions=4,2,1";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0xB/0x0F actions=3,2,1";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0xD/0x0F actions=3,4,1";
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=1,priority=10,vxlan__grp0Id_grp0Bitmask=0xE/0x0F actions=3,4,2";
         cd /root
  when: 'inventory_hostname == "prme-nsx-perf-004"'

- name: add flow rules for group matching
  shell: cd /root/ovs/utilities;
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 "table=0,priority=100,ethernet__etherType=0x0800,ipv4__protocol=17,udp__dstPort=4789,vxlan__grp0Id_grp0Bitmask=0x10/0xF0 actions=resubmit(,1)"
  when: 'inventory_hostname == "prme-nsx-perf-004"'