---

#- name: remove paho-mqtt
#  become: true
#  pip:
#    name: paho-mqtt
#    state: absent
#
#- name: remove python-pip
#  become: true
#  apt:
#    name: python-pip
#    purge: yes
#    state: absent

- name: remove mosquitto-clients
  become: true
  apt:
    name: mosquitto-clients
    purge: yes
    state: absent

- name: remove mosquitto
  become: true
  apt:
    name: mosquitto
    purge: yes
    state: absent
  when: '"broker" in pubsub_nodes[inventory_hostname]["type"] and pubsub_nodes[inventory_hostname].enable'

- name: remove mosquitto repository
  shell: apt-add-repository --remove ppa:mosquitto-dev/mosquitto-ppa
  become: true

- name: update cache
  become: true
  apt:
    update_cache: yes
