---

nodes:
  prme-nsx-perf-004:
    interfaces:
      - eth2 # prme-nsx-perf-001
      - eth5 # prme-nsx-perf-002
      - eth8 # prme-nsx-perf-003
      - eth9 # prme-nsx-perf-005:eth2
#      - eth6 # prme-nsx-perf-005:eth5
#      - eth7 # prme-nsx-perf-005:eth8
    options:
      eth2:
        pci_id: "0000:41:00.0"
        if_index: 1 # NOTE: for some reason this is assigned in the order of eth ids (e.g., eth2=1, eth5=2, and eth8=3).
      eth5:
        pci_id: "0000:41:00.1"
        if_index: 2
      eth8:
        pci_id: "0000:44:00.0"
        if_index: 3
      eth9:
        pci_id: "0000:44:00.1"
        if_index: 4
#      eth6:
#        pci_id: "0000:43:00.0"
#        if_index: -
#      eth7:
#        pci_id: "0000:43:00.1"
#        if_index: -
  prme-nsx-perf-006:
    interfaces:
      - eth8 # prme-nsx-perf-007
      - eth1 # prme-nsx-perf-008
      - eth4 # prme-nsx-perf-009
      - eth7 # prme-nsx-perf-005:eth6
#      - eth9 # prme-nsx-perf-005:eth7
#      - eth6 # prme-nsx-perf-005:eth9
    options:
      eth8:
        pci_id: "0000:42:00.0"
        if_index: 4
      eth1:
        pci_id: "0000:04:00.0"
        if_index: 1 # NOTE: for some reason this is assigned in the order of eth ids (e.g., eth8=3, eth1=1, and eth4=2).
      eth4:
        pci_id: "0000:04:00.1"
        if_index: 2
      eth7:
        pci_id: "0000:41:00.1"
        if_index: 3
#      eth9:
#        pci_id: "0000:42:00.1"
#        if_index: -
#      eth6:
#        pci_id: "0000:41:00.0"
#        if_index: -

switches:
  pisces:
    cflags: '-Ofast -march=native -Wno-cast-align'
    cpu_mask: '0xFFF0'
    memory_channels: 4
    p4_programs:
      base_dir: files
  ovs_dpdk:
    cflags: '-Ofast -march=native -Wno-cast-align' # Options: -g or ''
    cpu_mask: '0xFFF0'
    memory_channels: 4
