---

- name: provision proxmox VMs
  hosts:  #mshahbaz-poweredge-1-pve,
          mshahbaz-poweredge-2-pve
         ,mshahbaz-poweredge-3-pve
  gather_facts: true

  vars_files:
    - "vars/proxmox.yml"

  roles:
    - proxmox
