---

- name: provision proxmox VMs
  hosts: mshahbaz-poweredge-2-pve, mshahbaz-poweredge-3-pve # Update this for other proxmox nodes
  gather_facts: true

  vars_files:
    - "vars/proxmox.yml"

  roles:
    - proxmox
