---

- name: Test
  hosts: pve*-servers
  gather_facts: false

  tasks:
    - debug:
        msg: "{{ inventory_file }}"

    - apt:
        name: bridge-utils
        update_cache: yes
      become: true

    - copy:
        src: ./keys/pu_pve_vm_rsa
        dest: ~/.ssh/id_rsa
        mode: 0600