---

- name: destroy sflow stats script
  shell: pkill -u root -f ifstat
  when: 'inventory_hostname in "prme7-k8s-node-120"'
  failed_when: false
  become: true

#- name: stop and destroy sflowtrend docker
#  shell: docker stop sflowtrend;
#         docker rm sflowtrend
#  when: 'inventory_hostname in "prme2-k8s-node-120" or
#         inventory_hostname in "prme3-k8s-node-120" or
#         inventory_hostname in "prme7-k8s-node-120" or
#         inventory_hostname in "prme8-k8s-node-120"'
#  become: true

- name: stop hsflowd service
  service:
    name: hsflowd
    state: stopped
  when: 'inventory_hostname in "prme7-k8s-node-120"'
  become: true

- name: remove hsflowd
  apt:
    name: hsflowd
    purge: yes
    state: absent
  when: 'inventory_hostname in "prme7-k8s-node-120"'
  become: true

- name: remove hsflowd debian files
  file:
    path: /home/mshahbaz/hsflowd-ubuntu14_2.0.11-1_amd64.deb
    state: absent
  when: 'inventory_hostname in "prme7-k8s-node-120"'
  become: true
