---

- name: create an ovs bridge br0
  shell: cd /root/ovs/utilities;
         ./ovs-vsctl add-br br0 -- set bridge br0 datapath_type=netdev;
         ./ovs-vsctl set bridge br0 protocols=OpenFlow15;
         cd /root

- name: bring up br0
  shell: ip link set dev br0 up

- name: add interfaces to br0
  shell: cd /root/ovs/utilities;
         ./ovs-vsctl add-port br0 dpdk{{ item }} -- set interface dpdk{{ item }} type=dpdk;
         cd /root
  with_sequence: start=0 end={{ nodes[inventory_hostname]['interfaces']|length - 1 }} format=%d

- name: delete existing flow rules
  shell: cd /root/ovs/utilities;
         ./ovs-ofctl --protocols=OpenFlow15 del-flows br0;
         cd /root

- name: add flow rules
  shell: cd /root/ovs/utilities;
         ./ovs-ofctl --protocols=OpenFlow15 add-flow br0 '{{ item }}';
         cd /root
  with_items: "{{ dc_switch.pisces.flow_rules[inventory_hostname] }}"
