---

- name: include overlay variables
  include_vars: roles/proxmox/defaults/networking/overlay.yml

- name: create an ovs bridge br0
  shell: cd /root/ovs/utilities;
         ./ovs-vsctl add-br br0 -- set bridge br0 datapath_type=netdev;
         ./ovs-vsctl set bridge br0 protocols=OpenFlow15;
         cd /root

- name: set mtu size to {{ proxmox_overlay_subnet_mtu_size }}
  command: ip link set mtu {{ proxmox_overlay_subnet_mtu_size }} dev br0

- name: bring up br0
  shell: ip link set dev br0 up

- name: add br0 to vmbr0 bridge
  shell: brctl addif vmbr0 br0

- name: add interfaces to br0
  shell: cd /root/ovs/utilities;
         ./ovs-vsctl add-port br0 dpdk0 -- set interface dpdk0 type=dpdk;
         cd /root

- name: delete existing flow rules
  shell: cd /root/ovs/utilities;
         ./ovs-ofctl --protocols=OpenFlow15 del-flows br0;
         cd /root

- name: create a veth link
  shell: ip link add {{ overlay[inventory_hostname]['interfaces'][network] }} type veth peer name br0-{{ overlay[inventory_hostname]['interfaces'][network] }};
         ip link set dev {{ overlay[inventory_hostname]['interfaces'][network] }} up;
         ip link set dev br0-{{ overlay[inventory_hostname]['interfaces'][network] }} up

- name: set veth ip adddress
  shell: ifconfig {{ item }} {{ overlay[inventory_hostname].options[item].address }} netmask {{ overlay[inventory_hostname].options[item].netmask }}
  with_items: "{{ overlay[inventory_hostname]['interfaces'][network] }}"

- name: add veth port to br0
  shell: cd /root/ovs/utilities;
         ./ovs-vsctl add-port br0 br0-eth5;
         cd /root

- name: add static route for overlay traffic
  shell: ip route add {{ proxmox_vm_network_address_prefix }}0.0/16 dev vmbr0

# Note: run br0_add_flow_rules to enable connectivity