---
apiVersion: v1
kind: Service
metadata:
  name: apache-servers
  labels:
    app: apache-servers
spec:
  ports:
    - port: 8080
  selector:
    app: apache-servers
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-servers
  labels:
    app: apache-servers
spec:
  replicas: 13
  template:
    metadata:
      labels:
        app: apache-servers
    spec:
      containers:
      - image: mshahbaz/apache:baseerat
        name: apache-servers
        volumeMounts:
        - name: logs
          mountPath: /var/logs
      volumes:
      - name: logs
        hostPath:
          path: /var/logs
