---

- name: add connection to radio.cpp
  lineinfile:
    path: /home/mshahbaz/libzmq/tests/radio.cpp
    line: 'rc = zmq_connect (radio, "udp://{{ ip }}:{{ port}}"); assert (rc == 0);'
    insertafter: '__insert_here__'
    state: present
  vars:
    ip: "{{ proxmox_vm_network_address_prefix }}{{ sub.prme_id }}.{{ sub.vm_id }}"
    port: "{{ pubsub_sub_port_base|int + item|int }}"
  with_sequence: start=0 end={{ sub.count|int - 1 }} format=%d
