---

- name: stop inf-loop-cpulimit-rand.sh scripts
  shell: pkill -u root -f inf-loop-cpulimit-rand.sh
  failed_when: false
  when: '"minion" in nodes[inventory_hostname]["type"] and workload.lb.nodes[inventory_hostname].nodetype == "apache"'
  delegate_to: prme-nsx-perf-00{{ prme_id }}

- name: stop left over inf-loop.sh scripts
  shell: pkill -u root -f inf-loop.sh
  failed_when: false
  when: '"minion" in nodes[inventory_hostname]["type"] and workload.lb.nodes[inventory_hostname].nodetype == "apache"'
  delegate_to: prme-nsx-perf-00{{ prme_id }}

- name: remove inf-loop.sh script
  file:
    path: /usr/local/bin/inf-loop.sh
    state: absent
  when: '"minion" in nodes[inventory_hostname]["type"] and workload.lb.nodes[inventory_hostname].nodetype == "apache"'
  delegate_to: prme-nsx-perf-00{{ prme_id }}

- name: remove inf-loop-cpulimit.sh script
  file:
    path: /usr/local/bin/inf-loop-cpulimit.sh
    state: absent
  when: '"minion" in nodes[inventory_hostname]["type"] and workload.lb.nodes[inventory_hostname].nodetype == "apache"'
  delegate_to: prme-nsx-perf-00{{ prme_id }}

- name: remove inf-loop-cpulimit-rand.sh script
  file:
    path: /usr/local/bin/inf-loop-cpulimit-rand.sh
    state: absent
  when: '"minion" in nodes[inventory_hostname]["type"] and workload.lb.nodes[inventory_hostname].nodetype == "apache"'
  delegate_to: prme-nsx-perf-00{{ prme_id }}
