---

- name: Remove repository key if installed
  apt_key:
    id: "{{ docker_apt_key_id }}"
    keyserver: "{{ docker_apt_keyserver }}"
    state: absent

- name: Remove docker registry if available
  # For Ubuntu 14.04 LTS, use this repository:
  apt_repository:
    repo: "{{ docker_apt_repo_14_04 }}"
    update_cache: yes
    state: absent
#  # For Ubuntu 16.04 LTS, use this repo instead:
#  apt_repository:
#    repo: "{{ docker_apt_repo_16_04 }}"
#    update_cache: yes
#    state: absent

- name: Uninstall docker and dependencies
  apt:
    name: docker-engine
    purge: yes
    state: absent

- name: Remove docker compose
  file:
    path: /usr/local/bin/docker-compose
    state: absent

#- debug:
#  msg: "{{inventory_hostname}}"
