---

#- name: cleanup memcached feedback set cmd
#  include: roles/workload/tasks/lb/feedback/cleanup/memcached/set_cmd.yml
#  when: 'workload.lb.apache_servers.feedback.type == "memcached"'

- name: cleanup zeromq feedback set cmd
  include: roles/workload/tasks/lb/feedback/cleanup/zeromq/set_cmd.yml
  when: 'workload.lb.apache_servers.feedback.type == "zeromq"'

- name: cleanup zeromq host feedback set cmd
  include: roles/workload/tasks/lb/feedback/cleanup/zeromq_host/set_cmd.yml
  when: 'workload.lb.apache_servers.feedback.type == "zeromq_host"'