---

- name: start etcd container
  docker_container:
    privileged: true
    network_mode: host
    pid_mode: host
    name: etcd
    image: gcr.io/google_containers/etcd:{{ etcd_version }}
    command:
      - "/usr/local/bin/etcd"
      - "--listen-client-urls=http://0.0.0.0:{{ k8s_etcd_port }}"
      - "--advertise-client-urls=http://0.0.0.0:{{ k8s_etcd_port }}"
      - "--data-dir={{ k8s_etcd_data_dir }}"
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: start api server
  docker_container:
    privileged: true
    network_mode: host
    pid_mode: host
    name: apiserver
    image: gcr.io/google_containers/hyperkube-amd64:v{{ k8s_version }}
    command:
      - "/hyperkube apiserver"
      - "--insecure-bind-address=0.0.0.0"
      - "--insecure-port={{ k8s_api_server_port }}"
      - "--service-cluster-ip-range={{ k8s_api_server_service_cluster_ip_range }}"
      - "--etcd-servers=http://localhost:{{ k8s_etcd_port }}"
      - "--v=2"
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: start controller manager
  docker_container:
    privileged: true
    network_mode: host
    pid_mode: host
    name: controller-manager
    image: gcr.io/google_containers/hyperkube-amd64:v{{ k8s_version }}
    command:
      - "/hyperkube controller-manager"
      - "--master=http://localhost:{{ k8s_api_server_port }}"
      - "--v=2"
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: start scheduler
  docker_container:
    privileged: true
    network_mode: host
    pid_mode: host
    name: scheduler
    image: gcr.io/google_containers/hyperkube-amd64:v{{ k8s_version }}
    command:
      - "/hyperkube scheduler"
      - "--master=http://localhost:{{ k8s_api_server_port }}"
      - "--v=2"
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: start kubelet
  docker_container:
    privileged: true
    network_mode: host
    pid_mode: host
    volumes:
      - "/:/rootfs:ro"
      - "/sys:/sys:ro"
      - "/dev:/dev"
      - "/var/lib/docker/:/var/lib/docker:rw"
      - "/var/lib/kubelet/:/var/lib/kubelet:rw"
      - "/var/run:/var/run:rw"
    name: kubelet
    image: gcr.io/google_containers/hyperkube-amd64:v{{ k8s_version }}
    command:
      - "/hyperkube kubelet"
      - "--allow-privileged=true"
      - "--containerized"
      - "--enable-server"
      - "--hostname-override={{ inventory_hostname }}"
      - "--address=0.0.0.0"
      - "--api-servers=http://{{ k8s_node_address_prefix }}{{ nodes[inventory_hostname]['master']['prme_id'] }}.{{ nodes[inventory_hostname]['master']['vm_id'] }}:{{ k8s_api_server_port }}"
      - "--v=2"
#  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: start proxy
  docker_container:
    privileged: true
    network_mode: host
    name: proxy
    image: gcr.io/google_containers/hyperkube-amd64:v{{ k8s_version }}
    command:
      - "/hyperkube proxy"
      - "--master=http://{{ k8s_node_address_prefix }}{{ nodes[inventory_hostname]['master']['prme_id'] }}.{{ nodes[inventory_hostname]['master']['vm_id'] }}:{{ k8s_api_server_port }}"
      - "--v=2"
#  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: get kubectl
  get_url:
    url: "{{ k8s_kubectl_url }}"
    dest: /usr/local/bin/kubectl
    mode: 0755
  when: '"master" in nodes[inventory_hostname]["type"]'
