---

- name: remove etcd container
  docker_container:
    name: etcd
    state: absent
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: remove api server
  docker_container:
    name: apiserver
    state: absent
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: remove controller manager
  docker_container:
    name: controller-manager
    state: absent
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: remove scheduler
  docker_container:
    name: scheduler
    state: absent
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: remove kubelet
  docker_container:
    name: kubelet
    state: absent
  when: '"minion" in nodes[inventory_hostname]["type"]'
  become: true

#- name: remove proxy
#  docker_container:
#    name: proxy
#    state: absent
#  when: '"minion" in nodes[inventory_hostname]["type"]'
#  become: true

- name: clear ipvs table
  command: ipvsadm -C
#  when: '"minion" in nodes[inventory_hostname]["type"]'
  become: true

- name: remove kube-ipvs-proxy.py script
  file:
    path: /usr/local/bin/kube-ipvs-proxy.py
    state: absent
#  when: '"minion" in nodes[inventory_hostname]["type"]'
  become: true

- name: remove dummy interface ipvs0
  command: ip link del dev ipvs0
#  when: '"minion" in nodes[inventory_hostname]["type"]'
  become: true

- name: remove kubectl
  file:
    path: /usr/local/bin/kubectl
    state: absent

- name: flush iptable rules
  command: iptables -t nat -F
#  when: '"minion" in nodes[inventory_hostname]["type"]'
  become: true
