---

- name: clear apps' rules from ipvs table
  command: kube-ipvs-proxy.py {{ item.namespace }} {{ k8s_node_address_prefix }}{{ nodes[inventory_hostname]['master']['prme_id'] }}.{{ nodes[inventory_hostname]['master']['vm_id'] }}:{{ k8s_api_server_port }} clear {{ item.name }} {{ item.policy }}
  with_items: "{{ apps }}"
  when: '"minion" in nodes[inventory_hostname]["type"]'
  ignore_errors: yes
  become: true

- name: remove apps' configs
  file:
    path: /tmp/app.{{ item.name }}.yml
    state: absent
  with_items: "{{ apps }}"
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: delete apps' service
  shell: kubectl --namespace={{ item.namespace }} delete service {{ item.name }}
  with_items: "{{ apps }}"
  when: '"master" in nodes[inventory_hostname]["type"]'
  ignore_errors: yes
  become: true

- name: delete apps' deployment
  shell: kubectl --namespace={{ item.namespace }} delete deployment {{ item.name }}
  with_items: "{{ apps }}"
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true
