---

apps:
#  - name: kubernetes-dashboard
#    namespace: kube-system
#    policy: rr
  - name: hello-world
    namespace: default
    policy: rr
#  - name: httperf-clients
#    namespace: default
#    policy: rr
#  - name: apache-servers
#    namespace: default
#    policy: wrr