---

- name: provision kubernetes cluster
  hosts: prme*k8s-node-*
  gather_facts: false
  become: true

  vars_files:
    - "vars/kubernetes/main.yml"
    - "vars/kubernetes/networking.yml"
    - "vars/kubernetes/apps.yml"

  roles:
    - kubernetes
