---

- name: bring up prme-nsx-perf-001 facing interface (eth2) on prme-nsx-perf-004 node
  shell: ip link set dev eth2 up

- name: bring up prme-nsx-perf-002 facing interface (eth6) on prme-nsx-perf-004 node
  shell: ip link set dev eth6 up

- name: bring up prme-nsx-perf-003 facing interface (rename10) on prme-nsx-perf-004 node
  shell: ip link set dev rename10 up

- name: add prme-nsx-perf-001 facing interface to br0 on prme-nsx-perf-004 node
  openvswitch_port:
    bridge: br0
    port: eth2
    state: present

- name: add prme-nsx-perf-002 facing interface to br0 on prme-nsx-perf-004 node
  openvswitch_port:
    bridge: br0
    port: eth6
    state: present

- name: add prme-nsx-perf-003 facing interface to br0 on prme-nsx-perf-004 node
  openvswitch_port:
    bridge: br0
    port: rename10
    state: present
