

- name: get current date and time
  shell: 'date "+%Y%m%d%H%M%S.%6N"'
  register: current_date_time
  when: '"master" in nodes[inventory_hostname]["type"]'
  delegate_to: "{{ workload_local_host }}"

- name: create directory with date and time
  shell: ssh {{ workload_analyst_host }} mkdir -p {{ workload_analyst_path }}/apps/lb/{{ current_date_time.stdout }}
  when: '"master" in nodes[inventory_hostname]["type"]'
  delegate_to: "{{ workload_local_host }}"

- name: fetch results to local host
  shell: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r {{ ansible_user }}@{{ ansible_host }}:{{ workload_logs_dir }}/* /tmp/
  when: '"minion" in nodes[inventory_hostname]["type"]'
  delegate_to: "{{ workload_local_host }}"

- name: fetch results to analyst host
  shell: scp -r /tmp/ipvsadm_L_n* /tmp/httperf-clients-* {{ workload_analyst_host }}:{{ workload_analyst_path }}/apps/lb/{{ current_date_time.stdout }}
  when: '"master" in nodes[inventory_hostname]["type"]'
  delegate_to: "{{ workload_local_host }}"

- name: cleanup results on minions
  shell: cd {{ workload_logs_dir }}; rm -rf *
  when: '"minion" in nodes[inventory_hostname]["type"]'
  become: true

- name: cleanup results on local host
  shell: cd /tmp; rm -rf ipvsadm_L_n* httperf-clients-*
  when: '"master" in nodes[inventory_hostname]["type"]'
  delegate_to: "{{ workload_local_host }}"

