---

- name: get apache-servers' service address
  shell: kubectl --namespace={{ workload.lb.apache_servers.namespace }} get service apache-servers -o jsonpath={.spec.clusterIP}
  register: service_address
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: upload httperf-clients' configs
  template:
    src: roles/workload/templates/httperf-clients.yml.j2
    dest: /tmp/app.httperf-clients.yml
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true

- name: create httperf-clients' apps
  shell: kubectl apply -f /tmp/app.httperf-clients.yml
  when: '"master" in nodes[inventory_hostname]["type"]'
  become: true
