---

- name: ensure that {{ hostname }}-vms group exists in the inventory file
  lineinfile:
    path: "{{ inventory_file }}"
    line: "[{{ hostname }}-vms]"
    state: present
  delegate_to: localhost

- name: add VM to the {{ hostname }}-vms group in the inventory file
  lineinfile:
    path: "{{ inventory_file }}"
    line: "{{ proxmox_name_prefix }}{{ proxmox_prme_id }}-{{ proxmox_vm_hostname_prefix }}{{ proxmox_vm_id }} ansible_host={{ proxmox_vm_network_address_prefix }}{{ proxmox_prme_id }}.{{ proxmox_vm_id }} ansible_user={{ proxmox_vm_user }} ansible_ssh_common_args='{{ proxmox_ssh_common_args }}' prme_id={{ proxmox_prme_id }} vm_id={{ proxmox_vm_id }}"
    insertafter: "^\\[{{ hostname }}-vms\\]"
    state: present
  delegate_to: localhost
