---

broker:
  prme_id: 2
  vm_id: 120

broker_pub_cmds: 'msleep (1);' # e.g. msleep(1);

broker_pub_count_per_node: 128
broker_sub_count_per_node: 1

broker_pubsub_nodes:
  prme1-k8s-node-120:
    type: "publisher"
    broker: "{{ broker }}"
    count: "{{ broker_pub_count_per_node }}"

  prme2-k8s-node-120:
    type: "broker"
    subs:
      - prme_id: 3
        vm_id: 120
        count: "{{ broker_sub_count_per_node }}"
    host: "prme-nsx-perf-002"

  prme3-k8s-node-120:
    type: "subscriber"
    broker: "{{ broker }}"
    count: "{{ broker_sub_count_per_node }}"
