---

- name: remove static routes
  shell: ip route del {{ proxmox_vm_network_address_prefix }}0.0/24 \
         dev {{ nodes[inventory_hostname]['interfaces'][0] }}

- name: remove static ip addresses
  shell: ip addr del {{ proxmox_vm_network_address_prefix }}0.{{ prme_id }}/32 \
         dev {{ nodes[inventory_hostname]['interfaces'][0] }}

- name: bring down interfaces
  shell: ip link set dev {{ nodes[inventory_hostname]['interfaces'][0] }} down
