---

- name: bring up interfaces
  shell: ip link set dev {{ nodes[inventory_hostname]['interfaces'][0] }} up

- name: add static ip addresses
  shell: ip addr add {{ proxmox_vm_network_address_prefix }}0.{{ prme_id }}/32 \
         dev {{ nodes[inventory_hostname]['interfaces'][0] }}

- name: add static routes
  shell: ip route add {{ proxmox_vm_network_address_prefix }}0.0/24 \
         dev {{ nodes[inventory_hostname]['interfaces'][0] }}
