---

- name: cleanup {{ inventory_hostname }} as tor
  include: roles/proxmox_tor/tasks/networking/tor_network/nodes/{{ inventory_hostname }}/cleanup.yml
  when: 'inventory_hostname == "prme-nsx-perf-004"'

- name: bring down br0
  shell: ip link set dev br0 down

- name: disable stp on br0 # TODO: change this to flow rules
  command: ovs-vsctl set bridge br0 stp_enable=false

- name: delete ovs bridge br0
  openvswitch_bridge:
    bridge: br0
    state: absent

- name: remove common utilities
  include: roles/proxmox_tor/tasks/networking/common/remove.yml
