---

- name: install common utilities
  include: roles/proxmox_tor/tasks/networking/common/install.yml

- name: create an ovs bridge br0
  openvswitch_bridge:
    bridge: br0
    state: present

- name: enable stp on br0 # TODO: change this to flow rules
  command: ovs-vsctl set bridge br0 stp_enable=true

- name: bring up br0
  shell: ip link set dev br0 up

- name: setup {{ inventory_hostname }} as tor
  include: roles/proxmox_tor/tasks/networking/tor_network/nodes/{{ inventory_hostname }}/setup.yml
  when: 'inventory_hostname == "prme-nsx-perf-004"'
