---

- name: remove libzmq
  become: true
  shell: cd /home/mshahbaz/libzmq;
         make uninstall;
         ldconfig;
         cd ~/

- name: remove libzmq repository
  become: true
  file:
    path: /home/mshahbaz/libzmq
    state: absent

- name: remove htop
  become: true
  apt:
    name: htop
    purge: yes
    state: absent

- name: remove git
  become: true
  apt:
    name: git
    purge: yes
    state: absent

- name: remove build-essential
  become: true
  apt:
    name: build-essential
    purge: yes
    state: absent

- name: remove libtool
  become: true
  apt:
    name: libtool
    purge: yes
    state: absent

- name: remove pkg-config
  become: true
  apt:
    name: pkg-config
    purge: yes
    state: absent

- name: remove autoconf
  become: true
  apt:
    name: autoconf
    purge: yes
    state: absent

- name: remove cmake
  become: true
  apt:
    name: cmake
    purge: yes
    state: absent

- name: remove uuid-dev
  become: true
  apt:
    name: uuid-dev
    purge: yes
    state: absent

- name: update cache
  become: true
  apt:
    update_cache: yes
