---

- name: install pisces
  include: roles/benchmark_switch/tasks/networking/switches/pisces/build/setup.yml
  tags: install_pisces

- name: clean pisces
  include: roles/benchmark_switch/tasks/networking/switches/pisces/build/cleanup.yml
  tags: clean_pisces

- name: install ovs (dpdk)
  include: roles/benchmark_switch/tasks/networking/switches/ovs_dpdk/build/setup.yml
  tags: install_ovs_dpdk

- name: clean ovs (dpdk)
  include: roles/benchmark_switch/tasks/networking/switches/ovs_dpdk/build/cleanup.yml
  tags: clean_ovs_dpdk

- name: setup switch
  include: roles/benchmark_switch/tasks/networking/setup.yml
  tags: setup_switch

- name: cleanup switch
  include: roles/benchmark_switch/tasks/networking/cleanup.yml
  tags: cleanup_switch
