---

baseerat_ip_address: 192.168.200.200
baseerat_mac_address: "11:22:33:44:55:66"
baseerat_port: 12345

baseerat_interfaces:
  prme-nsx-perf-001: 2
  prme-nsx-perf-002: 1
  prme-nsx-perf-003: 1
  prme-nsx-perf-007: 1
  prme-nsx-perf-008: 1
  prme-nsx-perf-009: 1
