---

- name: launch sflow
  include: roles/sflow/tasks/sflow/launch.yml
  tags: launch_sflow

- name: destroy sflow
  include: roles/sflow/tasks/sflow/destroy.yml
  tags: destroy_sflow

- name: install common utilities
  include: roles/sflow/tasks/common/install.yml
  tags: install_common

- name: remove common utilities
  include: roles/sflow/tasks/common/remove.yml
  tags: remove_common

